<script>
[
  {
    'name': 'sid',
    'title': 'Sid',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 1,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': false,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'sid') }
  },
  {
    'name': 'name',
    'title': 'Name',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 2,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 100,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'name') }
  },
  {
    'name': 'createTime',
    'title': 'CreateTime',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 3,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'datetime',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'createTime') }
  },
  {
    'name': 'deleted',
    'title': 'Deleted',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 4,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'bit',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'deleted') }
  },
  {
    'name': 'timestamp',
    'title': 'Timestamp',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 5,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'timestamp',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'timestamp') }
  },
  {
    'name': 'status',
    'title': 'Status',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 6,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 50,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'status') }
  },
  {
    'name': 'organizationID',
    'title': 'OrganizationID',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 7,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'organizationID') }
  },
  {
    'name': 'hierarchy',
    'title': 'Hierarchy',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 8,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'hierarchy') }
  },
  {
    'name': 'userID',
    'title': 'UserID',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 9,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': false,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'userID') }
  },
  {
    'name': 'categoryID',
    'title': 'CategoryID',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 10,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'categoryID') }
  },
  {
    'name': 'type',
    'title': 'Type',
    'fixed': false,
    'isCode': false,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 11,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'varchar',
    'maxLength': 36,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'type') }
  },
  {
    'name': 'brand',
    'title': 'Brand',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 12,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 50,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'brand') }
  },
  {
    'name': 'model',
    'title': 'Model',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 13,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 1000,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'model') }
  },
  {
    'name': 'price',
    'title': 'Price',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 14,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'decimal',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'price') }
  },
  {
    'name': 'description',
    'title': 'Description',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 15,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 2000,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'description') }
  },
  {
    'name': 'detail',
    'title': 'Detail',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 16,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': -1,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'detail') }
  },
  {
    'name': 'cost',
    'title': 'Cost',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 17,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'decimal',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'cost') }
  },
  {
    'name': 'best',
    'title': 'Best',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 18,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'bit',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'best') }
  },
  {
    'name': 'hot',
    'title': 'Hot',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 19,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'bit',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'hot') }
  },
  {
    'name': 'new',
    'title': 'New',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 20,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'bit',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'new') }
  },
  {
    'name': 'shipping',
    'title': 'Shipping',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 21,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'bit',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'shipping') }
  },
  {
    'name': 'unit',
    'title': 'Unit',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 22,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 50,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'unit') }
  },
  {
    'name': 'weight',
    'title': 'Weight',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 23,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 50,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'weight') }
  },
  {
    'name': 'volume',
    'title': 'Volume',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 24,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 50,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'volume') }
  },
  {
    'name': 'sell',
    'title': 'Sell',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 25,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'decimal',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'sell') }
  },
  {
    'name': 'stock',
    'title': 'Stock',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 26,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'decimal',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'stock') }
  },
  {
    'name': 'limit',
    'title': 'Limit',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 27,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'decimal',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'limit') }
  },
  {
    'name': 'praise',
    'title': 'Praise',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 28,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'numeric',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'praise') }
  },
  {
    'name': 'negative',
    'title': 'Negative',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 29,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'numeric',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'negative') }
  },
  {
    'name': 'picture',
    'title': 'Picture',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 30,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'nvarchar',
    'maxLength': 2000,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'picture') }
  },
  {
    'name': 'expires',
    'title': 'Expires',
    'fixed': false,
    'isCode': true,
    'codeSID': '',
    'codeSource': '',
    'present': null,
    'multiSelection': false,
    'position': 31,
    'width': 150,
    'tableWidth': 0,
    'dataType': 'datetime',
    'maxLength': 0,
    'nullable': true,
    'listable': true,
    'creatable': true,
    'queryable': true,
    'queryValue': null,
    'formValue': null,
    'handleChange': function(value) { GlogbalObj.handleChange(value, 'expires') }
  }
]
</script>
