const Fields = [{
  name: 'sid',
  title: '内部代码',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 1,
  width: 200,
  tableWidth: 120,
  dataType: 'varchar',
  maxLength: 36,
  nullable: false,
  listable: true,
  creatable: false,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'sid')
  }
},
{
  name: 'levelID',
  title: '代码层级',
  fixed: false,
  isCode: true,
  codeSID: '1089764a91421000',
  codeSource: '',
  present: 'cascader',
  multiSelection: true,
  position: 1,
  width: 300,
  tableWidth: 120,
  dataType: 'varchar',
  maxLength: 36,
  nullable: false,
  listable: true,
  creatable: true,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'levelID')
  }
},
{
  name: 'name',
  title: '代码名称',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 2,
  width: 220,
  tableWidth: 120,
  dataType: 'nvarchar',
  maxLength: 100,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'name')
  }
},
{
  name: 'name_EN',
  title: '英文名称',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 2,
  width: 220,
  tableWidth: 120,
  dataType: 'nvarchar',
  maxLength: 100,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'name_EN')
  }
},
{
  name: 'sort',
  title: '排序',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 3,
  width: 220,
  tableWidth: 60,
  dataType: 'smallint',
  maxLength: '',
  nullable: true,
  listable: true,
  creatable: true,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'sort')
  }
}, {
  name: 'value',
  title: '代码值',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 3,
  width: 180,
  tableWidth: 180,
  dataType: 'nvarchar',
  maxLength: 0,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'value')
  }
}, {
  name: 'comment',
  title: '备注',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 4,
  width: 360,
  tableWidth: 80,
  dataType: 'nvarchar',
  maxLength: 0,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'comment')
  }
}, {
  name: 'createTime',
  title: '创建时间',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 12,
  width: 0,
  tableWidth: 160,
  dataType: 'datetime',
  maxLength: 0,
  nullable: true,
  listable: true,
  creatable: false,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'createTime')
  }
}, {
  name: 'deleted',
  title: 'Deleted',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 5,
  width: 0,
  tableWidth: 0,
  dataType: 'bit',
  maxLength: 0,
  nullable: true,
  listable: false,
  creatable: false,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'deleted')
  }
}, {
  name: 'timestamp',
  title: 'Timestamp',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 6,
  width: 0,
  tableWidth: 0,
  dataType: 'timestamp',
  maxLength: 0,
  nullable: true,
  listable: false,
  creatable: false,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'timestamp')
  }
}, {
  name: 'status',
  title: '代码状态',
  fixed: false,
  isCode: true,
  codeSID: '109a458e15021000',
  codeSource: '',
  present: 'selection',
  multiSelection: false,
  position: 7,
  width: 200,
  tableWidth: 100,
  dataType: 'nvarchar',
  maxLength: 0,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'status')
  }
}, {
  name: 'parentID',
  title: '父级代码',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: true,
  position: 8,
  width: 260,
  tableWidth: 120,
  dataType: 'varchar',
  maxLength: 36,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'parentID')
  }
}, {
  name: 'catalog',
  title: '代码类别',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 5,
  width: 220,
  tableWidth: 80,
  dataType: 'nvarchar',
  maxLength: 0,
  nullable: true,
  listable: true,
  creatable: true,
  queryable: true,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'catalog')
  }
}, {
  name: 'organizationID',
  title: '代码所属机构',
  fixed: false,
  isCode: false,
  codeSID: '',
  codeSource: '',
  present: null,
  multiSelection: false,
  position: 10,
  width: 0,
  tableWidth: 0,
  dataType: 'varchar',
  maxLength: 36,
  nullable: true,
  listable: false,
  creatable: false,
  queryable: false,
  queryValue: null,
  formValue: null,
  handleChange: function(value) {
    window.GlogbalObj.handleChange(value, 'organizationID')
  }
}
]
export default Fields
